coslr: false
criterions:
  PerformanceLoss:
    def_file: ./loss/EnergyDebiasMosLoss.py
    loss_params: {tau: 1.0}
    optim_params: null
    weight: 1.0
endlr: 0.0
last: false
memory:
  centroids: false
  init_centroids: false
model_dir: null
networks:
  classifier:
    def_file: /models/EnergyMosClassifier.py
    optim_params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0002
      milestones:
      - - 1.0
        - 4
      - - 0.01
        - 160
      - - 0.0001
        - 180
      step_per_epoch: 96
    params:
      dataset: cifar10-lt-im100
      feat_dim: 64
      log_dir: ./logs/cifar10_im100_resnet32_e200/logits_adjustment/lr0.1_gpu1_bs128
      num_classes: 10
      stage1_weights: false
      test: false
  feat_model:
    def_file: ./models/resnetcifar10.py
    fix: false
    optim_params:
      lr: 0.1
      momentum: 0.9
      weight_decay: 0.0002
      milestones:
      - - 1.0
        - 4
      - - 0.01
        - 160
      - - 0.0001
        - 180
      step_per_epoch: 96
    params:
      dataset: cifar10-lt-im100
      dropout: null
      log_dir: ./logs/cifar10_im100_resnet32_e200/logits_adjustment/lr0.1_gpu1_bs128
      num_classes: 10
      stage1_weights: false
      test: false
      use_fc: false
      use_selfatt: false
shuffle: false
training_opt:
  backbone: resnet32
  batch_size: 128
  dataset: cifar10-lt-im100
  display_step: 10
  feature_dim: 64
  log_dir: ./logs/cifar10_im100_resnet32_e200/logits_adjustment/lr0.1_gpu1_bs128
  log_root: ./logs/cifar10_im100_resnet32_e200
  num_classes: 10
  num_epochs: 200
  num_workers: 12
  open_threshold: 0.1
  sampler: null
  scheduler_params:
    gamma: 0.1
    step_size: 30
  stage: resnet32_uniform_e200
  sub_dir: models
warmup: true

